spring.datasource.url=jdbc:mysql://localhost:3306/sistemaweb_senai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=sistemasenaiuser
spring.datasource.password=sistemasenaiuser
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


